### ISSUE TITLE
5 timestep issue for train and live

### ISSUE THREAD

**Issue by apatel726** [apatel726/HurricaneDissertation#22]
Fix code to train on 5 total timesteps (30 hours total) 

- Fix run and bd_lstm file and datautils file
-Fix deploy file for time lag

**Comment by hammad93** [comment]
Per our conversation, we might want to do 6 hour timesteps instead

**Comment by hammad93** [comment]
we were able to filter if the length of the entries are more than or equal to 20. the delta between each entry is 6 hours

**Comment by apatel726** [comment]
fixed model to allow for 6 hour timesteps in labels and overvations over 5 timesteps - however loss for every epoch is 0

**Comment by hammad93** [comment]
This was solved and the solution is available in the master branch. Closing.
