### ISSUE TITLE
Unable to plot Cartopy for Singular Lat

### ISSUE THREAD

**Issue by apatel726** [apatel726/HurricaneDissertation#36]
6 hours: universal result lat test:29.970962369441988
12 hours: universal result lat test:30.520224204659463
18 hours: universal result lat test:31.017637380957606
24 hours: universal result lat test:31.505104526877403
30 hours: universal result lat test:32.000987741351125
{'AL022019': {'lat': [29.970962369441988,
                      30.520224204659463,
                      31.017637380957606,
                      31.505104526877403,
                      32.000987741351125],
              'lon': [],
              'name': 'AL022019',
              'times': [Timestamp('2019-07-13 21:00:00+0000', tz='UTC'),
                        Timestamp('2019-07-14 03:00:00+0000', tz='UTC'),
                        Timestamp('2019-07-14 09:00:00+0000', tz='UTC'),
                        Timestamp('2019-07-14 15:00:00+0000', tz='UTC'),
                        Timestamp('2019-07-14 21:00:00+0000', tz='UTC')],
              'wind': []}}
Traceback (most recent call last):
  File "test.py", line 64, in <module>
    plotting_utils.process_results({'inference' : inference, 'track' : args.test})
  File "/tf/HurricaneDissertation/hurricane_ai/plotting_utils.py", line 98, in process_results
    ax.plot([storm['lon'][index - 1], storm['lon'][index]], [storm['lat'][index - 1], storm['lat'][index]],
IndexError: list index out of range
root@4687f5a136f3:/tf/HurricaneDissertation#

**Comment by hammad93** [comment]
Fixed in `all_timesteps` branch, pending merge to master in the future
